const chai = require("chai");
const asPromised = require("chai-as-promised");
chai.use(asPromised);
const expect = chai.expect;

const container = require("../../dependencies/testReportDependencies");
const { testReportWebHookApi } = require("../../controllers/testReport")(
  container
);
const { findById } = require("../../repos/testReportRepo");

const testReportPayload = {
  "Signing Doctor": [
    {
      "Signing Doctor 1": "Test Doctor 2",
    },
  ],
  orderNumber: "",
  "Patient Name": "Manjeet P",
  fileInputReport: 0,
  labPatientId: "7977428872",
  "Test Name": "COVID-19 Screening (Nucleic Acid Amplification, Qualitative)",
  CentreReportId: 66138383,
  integrationCode: "8033",
  billReferral: "SELF",
  labId: 2675,
  "Sample Date": "2020-03-26T18:29:49Z",
  billId: 477,
  dictionaryId: 1515,
  "Report Id": 3200926,
  reportFormatAndValues: [
    {
      highlight: 0,
      value: "Detected",
      reportFormat: {
        isImage: 0,
        lowerBoundFemale: "-",
        criticalUpperFemale: "-",
        descriptionFlag: 0,
        lowerBoundMale: "-",
        listField: 1,
        otherFemale: "-",
        criticalLowerMale: "-",
        otherFlag: 0,
        highlightFlag: 0,
        upperBoundFemale: "-",
        testName:
          "COVID-19 Screening (Nucleic Acid Amplification, Qualitative)",
        dictionaryId: 1515,
        otherMale: "-",
        upperBoundMale: "-",
        testUnit: "-",
        fileInput: 0,
        integrationCode: "",
        criticalUpperMale: "-",
        method: "",
        criticalLowerFemale: "-",
      },
    },
  ],
  "Report Date": "2020-03-26T18:58:04Z",
  status: "Report Submit (With Values)",
  testCode: "COVID",
  Gender: "Male",
  Age: "33 years",
  "Accession Date": "2020-03-26T18:42:32Z",
  isSigned: 1,
  webhookId: 15,
  "Patient Id": 355,
  labReportId: 66138383,
  reportDate: "2020-03-26T18:58:09Z",
  alternateEmail: null,
  "Approval Date": "2020-03-26T18:58:04Z",
  "Contact No": "",
  testID: 3200926,
};
const test2 = {
  "Signing Doctor": [
    {
      "Signing Doctor 1": "Test Doctor 2",
    },
  ],
  orderNumber: "order123",
  "Patient Name": "Test Patinet",
  fileInputReport: 0,
  labPatientId: "9876543210",
  "Test Name": "COVID-19 Virus QUALITATIVE PCR",
  CentreReportId: 66394120,
  integrationCode: "",
  billReferral: "SELF",
  labId: 2675,
  "Sample Date": "2020-04-06T10:32:16Z",
  billId: 3536,
  dictionaryId: 1515,
  "Report Id": 3210803,
  reportFormatAndValues: [
    {
      highlight: 0,
      value: "Negative",
      reportFormat: {
        isImage: 0,
        lowerBoundFemale: "-",
        criticalUpperFemale: "-",
        descriptionFlag: 0,
        lowerBoundMale: "-",
        listField: 1,
        otherFemale: "Negative",
        criticalLowerMale: "-",
        highlightFlag: 0,
        upperBoundFemale: "-",
        otherFlag: 1,
        testName: "E-Sarbeco Gene",
        criticalUpperMale: "-",
        otherMale: "Negative",
        upperBoundMale: "-",
        testUnit: "-",
        fileInput: 0,
        integrationCode: "",
        dictionaryId: null,
        method: "",
        criticalLowerFemale: "-",
      },
    },
    {
      highlight: 0,
      value: "Negative",
      reportFormat: {
        isImage: 0,
        lowerBoundFemale: "-",
        criticalUpperFemale: "-",
        descriptionFlag: 0,
        lowerBoundMale: "-",
        listField: 1,
        otherFemale: "Negative",
        criticalLowerMale: "-",
        highlightFlag: 0,
        upperBoundFemale: "-",
        otherFlag: 1,
        testName: "RdRP Gene",
        criticalUpperMale: "-",
        otherMale: "Negative",
        upperBoundMale: "-",
        testUnit: "-",
        fileInput: 0,
        integrationCode: "",
        dictionaryId: null,
        method: "",
        criticalLowerFemale: "-",
      },
    },
    {
      highlight: 0,
      value: "Negative",
      reportFormat: {
        isImage: 0,
        lowerBoundFemale: "-",
        criticalUpperFemale: "-",
        descriptionFlag: 0,
        lowerBoundMale: "-",
        listField: 1,
        otherFemale: "Negative",
        criticalLowerMale: "-",
        highlightFlag: 0,
        upperBoundFemale: "-",
        otherFlag: 1,
        testName: "RNASE P",
        criticalUpperMale: "-",
        otherMale: "Negative",
        upperBoundMale: "-",
        testUnit: "-",
        fileInput: 0,
        integrationCode: "",
        dictionaryId: null,
        method: "",
        criticalLowerFemale: "-",
      },
    },
    {
      highlight: 0,
      value: "Inconclusive",
      reportFormat: {
        isImage: 0,
        lowerBoundFemale: "-",
        criticalUpperFemale: "-",
        descriptionFlag: 1,
        lowerBoundMale: "-",
        listField: 0,
        otherFemale: "-",
        criticalLowerMale: "-",
        highlightFlag: 0,
        upperBoundFemale: "-",
        otherFlag: 0,
        testName: "Conclusion",
        criticalUpperMale: "-",
        otherMale: "-",
        upperBoundMale: "-",
        testUnit: "-",
        fileInput: 0,
        integrationCode: "",
        dictionaryId: null,
        method: "",
        criticalLowerFemale: "-",
      },
    },
    {
      highlight: 0,
      value:
        '<table border="1" cellpadding="2" cellspacing="0" style="width:80%">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td style="width:40%"><strong>RESULT</strong></td>\n\t\t\t<td style="width:40%"><strong>REMARKS</strong></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Positive for E-Sarbeco, RdRP &amp; RNase P</td>\n\t\t\t<td>Positive for Covid-19 Virus</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Only RNase P positive</td>\n\t\t\t<td>Negative for Covid-19 Virus</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Positive for E-Sarbeco and RNAse P</td>\n\t\t\t<td>Inconclusive. As per guidelines a repeat sample is recommended.</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>RNase P negative</td>\n\t\t\t<td>Repeat sample is recommended</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Positive for RdRP and RNAse P</td>\n\t\t\t<td>Inconclusive. As per guidelines a repeat sample is&nbsp;recommended.</td>\n\t\t</tr>\n\t</tbody>\n</table>\n\n<div>&nbsp;</div>\n',
      reportFormat: {
        isImage: 0,
        lowerBoundFemale: "-",
        criticalUpperFemale: "-",
        descriptionFlag: 1,
        lowerBoundMale: "-",
        listField: 0,
        otherFemale: "-",
        criticalLowerMale: "-",
        highlightFlag: 0,
        upperBoundFemale: "-",
        otherFlag: 0,
        testName: "Interpretation",
        criticalUpperMale: "-",
        otherMale: "-",
        upperBoundMale: "-",
        testUnit: "#",
        fileInput: 0,
        integrationCode: "",
        dictionaryId: null,
        method: "",
        criticalLowerFemale: "-",
      },
    },
    {
      highlight: 0,
      value:
        "<ol>\n\t<li>Negative result does not rule out the possibility of Covid-19 infection. Presence of inhibitors, mutations &amp; insufficient organism RNA can influence the result</li>\n\t<li>RNase P serves as an internal control</li>\n\t<li>Covid-19 Test conducted as per protocol of Govt. of India</li>\n\t<li>Kindly consult referring Physician / Authorized Govt. hospital for appropriate followup</li>\n</ol>\n<strong>Comments</strong><br />\nCoronaviruses (CoV) are a large family of viruses that cause illness ranging from the common cold to more severe diseases such as Middle East Respiratory Syndrome (MERS-CoV) and Severe Acute Respiratory Syndrome (SARS-CoV). Coronavirus disease (COVID-19) is a new strain that was discovered in 2019 and has not been previously identified in humans. Common signs of infection include respiratory symptoms,fever, cough, shortness of breath and breathing difficulties. In more severe cases, infection can cause pneumonia, severe acute respiratory syndrome and kidney failure. This assay targets both the E-gene which is recommended as a first line test and the RdRP gene which is recommended as the confirmatory test.",
      reportFormat: {
        isImage: 0,
        lowerBoundFemale: "-",
        criticalUpperFemale: "-",
        descriptionFlag: 1,
        lowerBoundMale: "-",
        listField: 0,
        otherFemale: "-",
        criticalLowerMale: "-",
        highlightFlag: 1,
        upperBoundFemale: "-",
        otherFlag: 0,
        testName: "Note",
        criticalUpperMale: "-",
        otherMale: "-",
        upperBoundMale: "-",
        testUnit: "#",
        fileInput: 0,
        integrationCode: "",
        dictionaryId: null,
        method: "",
        criticalLowerFemale: "-",
      },
    },
  ],
  "Report Date": "2020-04-06T10:35:30Z",
  status: "Report Submit (With Values) covid-19",
  testCode: "COVID-19 Virus QUALITATIVE PCR",
  Gender: "Male",
  Age: "22",
  "Accession Date": "2020-04-06T10:32:21Z",
  isSigned: 1,
  webhookId: 36,
  "Patient Id": 5013,
  labReportId: 66394120,
  reportDate: "2020-04-06T10:37:04Z",
  alternateEmail: "",
  "Approval Date": "2020-04-06T10:35:30Z",
  "Contact No": "",
  testID: 3210803,
};

describe("Test Reports", () => {
  describe("AtestReportWebHookApiPI", () => {
    it("correct dictionary IDs and other data are written to the system", async () => {
      const { testReportId, status } = await testReportWebHookApi({
        provider: "test-integration",
        testReportPayload: test2,
      });
      await expect(findById(testReportId)).to.eventually.have.property(
        "testType",
        testReportPayload.dictionaryId + ""
      );
    });
  });
});
